-- PRUEBA TECNICA BACKEND
DROP TABLE EMPLEADO;
DROP TABLE DIRECCION;

-- TABLA EMPLEADO
CREATE TABLE EMPLEADO(
    NOMBRE NVARCHAR2(100) NOT NULL,
    APELLIDOS NVARCHAR2(100) NOT NULL,
    CURP NVARCHAR2(12), -- PK
    PUESTO NVARCHAR2(100) DEFAULT 'SIN PUESTO',
    CLAVE_JEFE_INMEDIATO NVARCHAR2(12) DEFAULT 'SIN JEFE',
    DIRECCION_ID NUMBER NOT NULL, -- FK
    CONSTRAINT EMPLEADO_PK PRIMARY KEY(CURP)
);

-- TABLA DIRECCION
CREATE TABLE DIRECCION(
    ID_DIRECCION NUMBER, -- PK
    CALLE NVARCHAR2(100) NOT NULL,
    NO_EXTERIOR NUMBER NOT NULL,
    NO_INTERIOR NUMBER DEFAULT 0,
    COLONIA NVARCHAR2(100) NOT NULL,
    MUNICIPIO NVARCHAR2(100) NOT NULL,
    ESTADO NVARCHAR2(100) NOT NULL,
    PAIS NVARCHAR2(100) NOT NULL,
    CONSTRAINT DIRECCION_PK PRIMARY KEY(ID_DIRECCION)
);






-- PRUEBAS
INSERT INTO EMPLEADO(NOMBRE,APELLIDOS,CURP,DIRECCION_ID) VALUES('IMANOL','URIBE','UIMI010413',1);

SELECT * FROM EMPLEADO;



INSERT INTO DIRECCION(ID_DIRECCION,CALLE,NO_EXTERIOR,COLONIA,MUNICIPIO,ESTADO,PAIS) VALUES(1,'CALLE VALLE GOMEZ',1,'FRANCISCO DE QUEVEDO','TEMACO','ESTADO DE MEXICO','MEXICO');

SELECT * FROM DIRECCION;


COMMIT;